"""add full text search vector and gin index

Revision ID: 1b815a8a42c7
Revises: 
Create Date: 2026-08-15 23:17:04.845839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b815a8a42c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', question || ' ' || answer)", persisted=True), nullable=True))
        batch_op.create_index('idx_chat_search', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_search', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
